// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Niculae_Ana_Maria_Proiect.Data;

#nullable disable

namespace Niculae_Ana_Maria_Proiect.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20240114104953_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Comentariu", b =>
                {
                    b.Property<int>("ComentariuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentariuId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProiectId")
                        .HasColumnType("int");

                    b.Property<int?>("SarcinaId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComentariuId");

                    b.HasIndex("ProiectId");

                    b.HasIndex("SarcinaId");

                    b.ToTable("Comentarii");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("Manageri");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.MembruEchipa", b =>
                {
                    b.Property<int>("MembruEchipaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembruEchipaId"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MembruEchipaId");

                    b.ToTable("MembriEchipa");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Proiect", b =>
                {
                    b.Property<int>("ProiectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProiectId"));

                    b.Property<DateTime?>("DataFinalizare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataIncepere")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProiectId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Proiecte");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Sarcina", b =>
                {
                    b.Property<int>("SarcinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SarcinaId"));

                    b.Property<DateTime?>("DataFinalizare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataIncepere")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProiectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SarcinaId");

                    b.HasIndex("ProiectId");

                    b.ToTable("Sarcini");
                });

            modelBuilder.Entity("SarcinaMembruEchipa", b =>
                {
                    b.Property<int>("SarcinaId")
                        .HasColumnType("int");

                    b.Property<int>("MembruEchipaId")
                        .HasColumnType("int");

                    b.HasKey("SarcinaId", "MembruEchipaId");

                    b.HasIndex("MembruEchipaId");

                    b.ToTable("SarcinaMembruEchipa");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Comentariu", b =>
                {
                    b.HasOne("Niculae_Ana_Maria_Proiect.Models.Proiect", "Proiect")
                        .WithMany("Comentarii")
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Niculae_Ana_Maria_Proiect.Models.Sarcina", "Sarcina")
                        .WithMany("Comentarii")
                        .HasForeignKey("SarcinaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Proiect");

                    b.Navigation("Sarcina");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Proiect", b =>
                {
                    b.HasOne("Niculae_Ana_Maria_Proiect.Models.Manager", "ManagerProiect")
                        .WithMany("Proiecte")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerProiect");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Sarcina", b =>
                {
                    b.HasOne("Niculae_Ana_Maria_Proiect.Models.Proiect", "ProiectAsociat")
                        .WithMany("Sarcini")
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProiectAsociat");
                });

            modelBuilder.Entity("SarcinaMembruEchipa", b =>
                {
                    b.HasOne("Niculae_Ana_Maria_Proiect.Models.MembruEchipa", null)
                        .WithMany()
                        .HasForeignKey("MembruEchipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niculae_Ana_Maria_Proiect.Models.Sarcina", null)
                        .WithMany()
                        .HasForeignKey("SarcinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Manager", b =>
                {
                    b.Navigation("Proiecte");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Proiect", b =>
                {
                    b.Navigation("Comentarii");

                    b.Navigation("Sarcini");
                });

            modelBuilder.Entity("Niculae_Ana_Maria_Proiect.Models.Sarcina", b =>
                {
                    b.Navigation("Comentarii");
                });
#pragma warning restore 612, 618
        }
    }
}
